#!/usr/bin/perl -w
# $Id: runTests,v 1.3 2002/10/30 10:45:31 vpapad Exp $

$temp = "tempresults";
if(-e $temp) {
   system("/bin/rm $temp");
}

@queries = <queries/*.qry>;
for $f (@queries) {
    #Remove "queries/" prefix 
    $f =~ s@[^/]*/@@;
    # Don't run the test if we don't know the expected results!
    next unless (-e "results/$f.result");
    print "$f\t";

    #Ugly! But how do you redirect stderr in a way that works
    #for both tcsh and bash? 
    `/bin/sh -c "./runSimple -silent -qf queries/$f 2>&1 >$temp"`;
    $diffs = system "cmp -s results/$f.result $temp";
    if ($diffs != 0) {
	print "FAILED\n";
	system "diff results/$f.result $temp";
    } else {
	print "OK\n";
    }
}
