##############################################################################
#
#  Makefile to build query engine related stuff
#
##############################################################################

clean:
	rm -rf yp.jar common.jar xmlql_parser.jar qe.jar qbe2.jar logicaloptree.jar dm.jar fsm.jar scan.jar


