#!/usr/local/bin/perl
#$Id: runSimple,v 1.7 2003/02/25 06:20:36 vpapad Exp $

use Cwd;

$niagroot = $ENV{"NIAGROOT"};

# if it is already set, leave it alone
if($niagroot eq "") {
    $niagroot = cwd();
    while (! -d "${niagroot}/demo" || ! -d "${niagroot}/lib") {
	    $niagroot =~ s!/[^/]*$!!;
 		die "ERROR: cannot find ancestor directory with demo and lib subdirectories\n"
 		if ($niagroot eq "");
    }
}

$niagroot .= "/";

# set classpath path
$classpath = `cat $niagroot/demo/classpath`;
$classpath =~ s/\n/ /;
$classpath =~ s/NIAGROOT\//$niagroot/g; 

$command = "java -classpath " . $classpath . 
           "niagara.client.SimpleClient " . join(" ", @ARGV) . "\n";
#print $command;
exec $command;
