#!/usr/bin/perl -w
# $Id: runFirehose,v 1.3 2003/02/22 08:03:37 tufte Exp $
system("rm -rf SYS/*");
system("rm -rf CACHE/*");

$classpath = `cat ../classpath`;
$classpath =~ s/\n/ /g;
$classpath =~ s/NIAGROOT\//\.\.\/\.\.\//g;

$command = "java -server -Xmx192m -classpath " . $classpath . 
           " niagara.firehose.XMLFirehose" . join(" ", @ARGV) ."\n"; 
#print $command;
exec $command;
