#!/usr/bin/perl -w

system("rm -rf CACHE/*");
system("rm -rf SYS/*");

$classpath = `cat ../classpath`;
$classpath =~ s/\n/ /g;
$classpath =~ s/NIAGROOT\//\.\.\/\.\.\//g;

$bootclasspath = `cat ../bootclasspath`;
$bootclasspath =~ s/\n/ /g;
$bootclasspath =~ s/NIAGROOT\//\.\.\/\.\.\//g;

$command = "java -Xbootclasspath/p:$bootclasspath -classpath " . $classpath . 
           " niagara.firehose.SimpleClient " . join(" ", @ARGV) ."\n";

#print $command;
exec $command;
