#!/usr/bin/perl -w
 
system("rm -rf SYS/*");
system("rm -rf CACHE/*");

$classpath = `cat ../classpath`;
$classpath =~ s/\n/ /g;
$classpath =~ s/NIAGROOT\//\.\.\/\.\.\//g;

$bootclasspath = `cat ../bootclasspath`;
$bootclasspath =~ s/\n/ /g;
$bootclasspath =~ s/NIAGROOT\//\.\.\/\.\.\//g;

$command = "java -Xbootclasspath/p:$bootclasspath -ea -server -Xmx192m -classpath " . $classpath . 
           " niagara.firehose.XMLFirehose " . join(" ", @ARGV) ."\n"; 
#print $command;
exec $command;
