#!/usr/bin/perl -w
# $Id: runRemoteDebug,v 1.2 2004/02/10 03:25:44 vpapad Exp $
system("rm -rf SYS/*");
system("rm -rf CACHE/*");

$classpath = `cat ../classpath`;
$classpath =~ s/\n/ /g;
$classpath =~ s/NIAGROOT\//\.\.\/\.\.\//g;

$bootclasspath = `cat ../bootclasspath`;
$bootclasspath =~ s/\n/ /g;
$bootclasspath =~ s/NIAGROOT\//\.\.\/\.\.\//g;

$command = "java -Xbootclasspath/p:$bootclasspath -server -ea -Xmx192m -Xdebug -Xnoagent " .
           " -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8001" .
	   " -classpath " . 
           $classpath . 
           " niagara.connection_server.NiagraServer " . 
	   join(" ", @ARGV) . "\n";
exec $command;
