#!/usr/bin/perl -w

# $Id: runServerProf,v 1.3 2003/07/03 19:24:57 tufte Exp $
system("rm -rf SYS/*");
system("rm -rf CACHE/*");

$classpath = `cat ../classpath`;
$classpath =~ s/\n/ /g;
$classpath =~ s/NIAGROOT\//\.\.\/\.\.\//g;


$ENV{"LD_LIBRARY_PATH"} = "../../lib";

$command = "java -ea -server -Xrunprofni:profile=yes,depth=4 " .
	   "-classpath " . $classpath . 
	   " niagara.connection_server.NiagraServer " .
	   join(" ", @ARGV) . " -without-se -run-niprof\n";
	   
exec $command;

#java -server -Xrunprofni:profile=yes,depth=4 -classpath `cat ../classpath` niagara.connection_server.NiagraServer $* -without-se -run-niprof
