#!/usr/bin/perl -w
# $Id: runServer,v 1.16 2003/07/18 19:36:48 tufte Exp $
system("rm -rf SYS/*");
system("rm -rf CACHE/*");

$classpath = `cat ../classpath`;
$classpath =~ s/\n/ /g;
$classpath =~ s/NIAGROOT\//\.\.\/\.\.\//g;

$command = "java -server -Xmx192m -classpath " . $classpath . 
           " niagara.connection_server.NiagraServer " . 
	   join(" ", @ARGV) . "\n";
exec $command;
