#!/usr/bin/perl -w
# $Id: runServer,v 1.15 2003/07/03 19:24:57 tufte Exp $
system("rm -rf SYS/*");
system("rm -rf CACHE/*");

$classpath = `cat ../classpath`;
$classpath =~ s/\n/ /g;
$classpath =~ s/NIAGROOT\//\.\.\/\.\.\//g;

$command = "java -server -ea -Xmx192m -classpath " . $classpath . 
           " niagara.connection_server.NiagraServer " . 
	   join(" ", @ARGV) . " -without-se\n";
#print $command;
exec $command;
