#!/usr/bin/perl -w
# $Id: runServerTimeOps,v 1.3 2004/02/10 03:25:44 vpapad Exp $

system("rm -rf SYS/*");
system("rm -rf CACHE/*");

$classpath = `cat ../classpath`;
$classpath =~ s/\n/ /g;
$classpath =~ s/NIAGROOT\//\.\.\/\.\.\//g;

$bootclasspath = `cat ../bootclasspath`;
$bootclasspath =~ s/\n/ /g;
$bootclasspath =~ s/NIAGROOT\//\.\.\/\.\.\//g;
 
$command = "java -Xbootclasspath/p:$bootclasspath -ea -server -Xmx192m -Xrunprofni:profile=no " .
           "-classpath " . $classpath .
           "niagara.connection_server.NiagraServer ".
	   join(" ", @ARGV) . " -without-se -time-operators\n";

$ENV{"LD_LIBRARY_PATH"} = "../../lib";

exec $command;

#java -server -Xmx192m -Xrunprofni:profile=no -classpath `cat ../classpath` niagara.connection_server.NiagraServer $* -without-se -time-operators
