#!/usr/bin/perl -w
# $Id: runServer,v 1.18 2007/06/01 18:54:26 jinli Exp $
system("rm -rf SYS/*");
system("rm -rf CACHE/*");

$classpath = `cat ../classpath`;
$classpath =~ s/\n/ /g;
$classpath =~ s/NIAGROOT\//\.\.\/\.\.\//g;

$bootclasspath = `cat ../bootclasspath`;
$bootclasspath =~ s/\n/ /g;
$bootclasspath =~ s/NIAGROOT\//\.\.\/\.\.\//g;
 
$command = "java -Xbootclasspath/p:$bootclasspath -server -Xmx192m -classpath " . $classpath . 
           " niagara.connection_server.NiagraServer -disable-buf-flush -saxdom-pages 5000 -accept-http -port 9050" . 
	   join(" ", @ARGV) . "\n";
exec $command;
