
//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Mon Oct 29 12:56:59 PDT 2007
//----------------------------------------------------

package niagara.xmlql_parser;

/** CUP generated class containing symbol constants. */
public class RESym {
  /* terminals */
  public static final int FUNCTION = 31;
  public static final int SLASH = 12;
  public static final int LPAREN = 8;
  public static final int STAR = 17;
  public static final int WHERE = 25;
  public static final int BAR = 19;
  public static final int RPAREN = 9;
  public static final int NOT = 23;
  public static final int AND = 22;
  public static final int LT = 2;
  public static final int IN = 24;
  public static final int OR = 21;
  public static final int QMARK = 15;
  public static final int COMMA = 13;
  public static final int GEQ = 6;
  public static final int PLUS = 16;
  public static final int DOT = 14;
  public static final int ID = 33;
  public static final int EOF = 0;
  public static final int CONFORM_TO = 30;
  public static final int error = 1;
  public static final int CONTENT_AS = 28;
  public static final int NUMBER = 37;
  public static final int NEQ = 7;
  public static final int EQ = 4;
  public static final int COLON = 18;
  public static final int ORDERED_BY = 29;
  public static final int LBRACE = 10;
  public static final int IDEQ = 34;
  public static final int IDEN = 35;
  public static final int DOLLAR = 20;
  public static final int RBRACE = 11;
  public static final int LEQ = 5;
  public static final int END = 32;
  public static final int CONSTRUCT = 26;
  public static final int STRING = 38;
  public static final int GT = 3;
  public static final int ELEMENT_AS = 27;
  public static final int VAR = 36;
}

