/* The following code was generated by JFlex 1.3.5 on 21/9/2003 6:11 �� */

package niagara.xmlql_parser;

import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.3.5
 * on 21/9/2003 6:11 �� from the specification file
 * <tt>file:/disk/hopper/projects/disc/niagara/vpapad/current/src/niagara/xmlql_parser/syntax_tree/xmlql.flex</tt>
 */
public class Scanner implements Lexer, java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  final public static int YYEOF = -1;

  /** initial size of the lookahead buffer */
  final private static int YY_BUFFERSIZE = 16384;

  /** lexical states */
  final public static int STRING = 1;
  final public static int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  final private static char [] yycmap = {
    11, 11, 11, 11, 11, 11, 11, 11, 11,  1, 13,  0,  0,  0, 11, 11, 
    11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,  0,  0,  0,  0, 
     1, 43, 12,  0,  9,  0,  0,  0, 33, 34,  3,  5, 37,  6,  7,  2, 
     4,  4,  4,  4,  4,  4,  4,  4,  4,  4, 39,  0, 41, 16, 42, 38, 
     0, 29, 30, 21, 15,  8, 32, 10, 19, 14, 10, 10, 26, 27, 17, 22, 
    10, 10, 20, 23, 24, 25, 10, 18, 10, 31, 10,  0,  0,  0,  0, 28, 
     0, 29, 30, 21, 15,  8, 32, 10, 19, 14, 10, 10, 26, 27, 17, 22, 
    10, 10, 20, 23, 24, 25, 10, 18, 10, 31, 10, 35, 40, 36,  0, 11
  };

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int yy_rowMap [] = { 
        0,    44,    88,   132,   176,    88,   220,   264,   264,    88, 
      308,   352,   396,    88,   440,    88,   484,   528,   572,   616, 
      660,   704,    88,    88,    88,    88,    88,    88,    88,    88, 
      748,   792,   836,   880,    88,   924,   968,  1012,  1056,  1100, 
     1144,  1188,  1232,   396,  1276,  1320,  1364,  1408,  1452,  1496, 
       88,    88,    88,  1540,  1584,  1628,  1672,   396,  1716,  1760, 
       88,   396,  1804,  1848,  1892,   396,  1936,  1980,  1628,  2024, 
     2068,  2112,  2156,  2200,  2244,  2288,  2332,   396,  2376,  2420, 
     2464,  2508,  2552,  2596,  2640,  2684,  2728,  2772,  2816,  2860, 
     2904,  2948,  2992,  3036,  3080,  3124,  3168,  3212,  3256,  3300, 
      396,  3344,   396,  3388,  3432,  3476,   396,   396,   396,   396
  };

  /** 
   * The packed transition table of the DFA (part 0)
   */
  final private static String yy_packed0 = 
    "\1\3\1\4\1\5\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\3\1\16\1\3\1\17\1\15"+
    "\1\20\1\21\1\22\2\15\1\23\1\24\5\15\1\3"+
    "\1\25\2\15\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\14\42\1\43"+
    "\1\3\36\42\55\0\1\4\55\0\1\44\54\0\1\7"+
    "\2\0\1\45\1\46\3\15\2\0\2\15\1\0\20\15"+
    "\17\0\1\47\53\0\1\15\3\0\4\15\2\0\2\15"+
    "\1\0\1\50\10\15\1\51\6\15\17\0\1\52\3\0"+
    "\1\52\1\0\1\52\3\0\2\52\1\0\13\52\1\0"+
    "\4\52\17\0\1\15\3\0\4\15\2\0\2\15\1\0"+
    "\20\15\17\0\1\15\3\0\4\15\2\0\1\15\1\53"+
    "\1\0\1\54\17\15\17\0\1\15\3\0\4\15\2\0"+
    "\2\15\1\0\5\15\1\55\12\15\17\0\1\15\3\0"+
    "\4\15\2\0\2\15\1\0\2\15\1\56\15\15\17\0"+
    "\1\15\3\0\4\15\2\0\2\15\1\0\5\15\1\57"+
    "\12\15\17\0\1\15\3\0\4\15\2\0\2\15\1\0"+
    "\3\15\1\60\14\15\17\0\1\15\3\0\4\15\2\0"+
    "\2\15\1\0\1\61\17\15\17\0\1\15\3\0\4\15"+
    "\2\0\2\15\1\0\10\15\1\62\7\15\33\0\1\63"+
    "\53\0\1\64\53\0\1\65\33\0\14\42\2\0\36\42"+
    "\3\66\1\0\50\66\4\0\1\67\53\0\1\15\2\70"+
    "\1\0\4\15\2\0\2\15\1\0\20\15\17\0\1\47"+
    "\2\0\1\45\1\71\47\0\1\15\3\0\4\15\2\0"+
    "\1\15\1\72\1\0\20\15\17\0\1\15\3\0\1\73"+
    "\3\15\2\0\2\15\1\0\20\15\17\0\1\52\3\0"+
    "\4\52\2\0\2\52\1\0\20\52\14\0\1\74\2\0"+
    "\1\15\3\0\4\15\2\0\2\15\1\75\20\15\17\0"+
    "\1\15\3\0\4\15\2\0\2\15\1\0\7\15\1\76"+
    "\10\15\17\0\1\15\3\0\1\77\3\15\2\0\2\15"+
    "\1\0\20\15\17\0\1\15\3\0\4\15\2\0\2\15"+
    "\1\0\1\100\17\15\17\0\1\15\3\0\4\15\2\0"+
    "\1\15\1\101\1\0\20\15\17\0\1\15\3\0\4\15"+
    "\2\0\1\15\1\102\1\0\20\15\17\0\1\15\3\0"+
    "\4\15\2\0\2\15\1\0\1\103\17\15\13\0\3\66"+
    "\1\104\50\66\4\0\1\67\3\0\1\71\47\0\1\105"+
    "\53\0\1\105\2\70\51\0\1\15\3\0\4\15\2\0"+
    "\2\15\1\0\12\15\1\106\5\15\14\0\1\74\16\0"+
    "\1\75\37\0\1\15\3\0\4\15\2\0\2\15\1\0"+
    "\3\15\1\107\14\15\17\0\1\15\3\0\4\15\2\0"+
    "\2\15\1\0\6\15\1\110\1\111\7\15\1\112\17\0"+
    "\1\15\3\0\1\113\3\15\2\0\2\15\1\0\20\15"+
    "\17\0\1\15\3\0\4\15\2\0\2\15\1\0\4\15"+
    "\1\114\13\15\13\0\2\66\1\3\1\104\50\66\4\0"+
    "\1\15\3\0\1\115\3\15\2\0\2\15\1\0\20\15"+
    "\17\0\1\15\3\0\1\116\3\15\2\0\2\15\1\0"+
    "\20\15\17\0\1\15\3\0\4\15\2\0\2\15\1\0"+
    "\7\15\1\117\10\15\17\0\1\15\3\0\1\120\3\15"+
    "\2\0\2\15\1\0\20\15\17\0\1\15\3\0\4\15"+
    "\2\0\2\15\1\0\5\15\1\121\12\15\17\0\1\15"+
    "\3\0\4\15\2\0\2\15\1\0\3\15\1\122\14\15"+
    "\17\0\1\15\3\0\4\15\2\0\2\15\1\0\7\15"+
    "\1\123\10\15\17\0\1\15\3\0\4\15\2\0\2\15"+
    "\1\0\1\124\17\15\17\0\1\15\3\0\4\15\2\0"+
    "\2\15\1\0\3\15\1\125\14\15\17\0\1\15\3\0"+
    "\4\15\2\0\2\15\1\0\1\126\17\15\17\0\1\15"+
    "\3\0\4\15\2\0\2\15\1\0\3\15\1\127\14\15"+
    "\17\0\1\15\3\0\1\130\3\15\2\0\2\15\1\0"+
    "\20\15\17\0\1\15\3\0\4\15\2\0\1\131\1\15"+
    "\1\0\20\15\17\0\1\15\3\0\4\15\2\0\2\15"+
    "\1\0\7\15\1\132\10\15\17\0\1\15\3\0\4\15"+
    "\2\0\2\15\1\0\10\15\1\133\7\15\17\0\1\15"+
    "\3\0\4\15\2\0\2\15\1\0\7\15\1\134\10\15"+
    "\17\0\1\15\3\0\4\15\2\0\2\15\1\0\12\15"+
    "\1\135\5\15\17\0\1\15\3\0\4\15\2\0\1\15"+
    "\1\136\1\0\20\15\17\0\1\15\3\0\4\15\2\0"+
    "\2\15\1\0\5\15\1\137\12\15\17\0\1\15\3\0"+
    "\4\15\2\0\2\15\1\0\13\15\1\140\4\15\17\0"+
    "\1\15\3\0\4\15\2\0\2\15\1\0\4\15\1\141"+
    "\13\15\17\0\1\15\3\0\4\15\2\0\2\15\1\0"+
    "\13\15\1\142\4\15\17\0\1\15\3\0\4\15\2\0"+
    "\2\15\1\0\13\15\1\143\4\15\17\0\1\15\3\0"+
    "\4\15\2\0\2\15\1\0\13\15\1\144\4\15\17\0"+
    "\1\15\3\0\4\15\2\0\2\15\1\0\1\145\17\15"+
    "\17\0\1\15\3\0\4\15\2\0\2\15\1\0\14\15"+
    "\1\146\3\15\17\0\1\15\3\0\4\15\2\0\2\15"+
    "\1\0\7\15\1\147\10\15\17\0\1\15\3\0\4\15"+
    "\2\0\2\15\1\0\14\15\1\150\3\15\17\0\1\15"+
    "\3\0\4\15\2\0\2\15\1\0\7\15\1\151\10\15"+
    "\17\0\1\15\3\0\4\15\2\0\2\15\1\0\15\15"+
    "\1\152\2\15\17\0\1\15\3\0\4\15\2\0\2\15"+
    "\1\0\6\15\1\153\11\15\17\0\1\15\3\0\4\15"+
    "\2\0\2\15\1\0\6\15\1\154\11\15\17\0\1\15"+
    "\3\0\4\15\2\0\2\15\1\0\5\15\1\155\12\15"+
    "\17\0\1\15\3\0\4\15\2\0\2\15\1\0\16\15"+
    "\1\156\1\15\13\0";

  /** 
   * The transition table of the DFA
   */
  final private static int yytrans [] = yy_unpack();


  /* error codes */
  final private static int YY_UNKNOWN_ERROR = 0;
  final private static int YY_ILLEGAL_STATE = 1;
  final private static int YY_NO_MATCH = 2;
  final private static int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  final private static String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private final static byte YY_ATTRIBUTE[] = {
     0,  0,  9,  1,  1,  9,  1,  1,  1,  9,  1,  1,  1,  9,  1,  9, 
     1,  1,  1,  1,  1,  1,  9,  9,  9,  9,  9,  9,  9,  9,  1,  1, 
     1,  1,  9,  0,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  9,  9,  9,  0,  1,  0,  0,  1,  1,  0,  9,  1,  1,  1, 
     1,  1,  1,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */
  StringBuffer string = new StringBuffer();
  String s = new String();
  private Symbol symbol(int type) {
	return new Symbol(type, yyline, yycolumn);
  	}

  private Symbol symbol(int type, Object value) {
	return new Symbol(type, yyline, yycolumn, value);
	}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Scanner(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Scanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[3520];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  final public void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  final public void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  final public int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  final public void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  final public String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  final public char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  final public int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() throws java.io.IOException {
    if (!yy_eof_done) {
      yy_eof_done = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      boolean yy_r = false;
      for (yy_currentPos_l = yy_startRead; yy_currentPos_l < yy_markedPos_l;
                                                             yy_currentPos_l++) {
        switch (yy_buffer_l[yy_currentPos_l]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          yy_r = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          yy_r = true;
          break;
        case '\n':
          if (yy_r)
            yy_r = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          yy_r = false;
          yycolumn++;
        }
      }

      if (yy_r) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean yy_peek;
        if (yy_markedPos_l < yy_endRead_l)
          yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        else if (yy_atEOF)
          yy_peek = false;
        else {
          boolean eof = yy_refill();
          yy_markedPos_l = yy_markedPos;
          yy_buffer_l = yy_buffer;
          if (eof) 
            yy_peek = false;
          else 
            yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        }
        if (yy_peek) yyline--;
      }
      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 25: 
          {  return symbol(sym.RBRACE);  }
        case 111: break;
        case 24: 
          {  return symbol(sym.LBRACE);  }
        case 112: break;
        case 23: 
          {  return symbol(sym.RPAREN);  }
        case 113: break;
        case 22: 
          {  return symbol(sym.LPAREN);  }
        case 114: break;
        case 11: 
          {  return symbol(sym.DOLLAR);  }
        case 115: break;
        case 6: 
        case 10: 
        case 12: 
        case 14: 
        case 16: 
        case 17: 
        case 18: 
        case 19: 
        case 20: 
        case 21: 
        case 37: 
        case 39: 
        case 40: 
        case 44: 
        case 45: 
        case 46: 
        case 48: 
        case 49: 
        case 58: 
        case 62: 
        case 63: 
        case 64: 
        case 66: 
        case 69: 
        case 70: 
        case 71: 
        case 72: 
        case 73: 
        case 74: 
        case 75: 
        case 76: 
        case 78: 
        case 79: 
        case 80: 
        case 81: 
        case 82: 
        case 83: 
        case 84: 
        case 85: 
        case 86: 
        case 87: 
        case 88: 
        case 89: 
        case 90: 
        case 91: 
        case 92: 
        case 93: 
        case 94: 
        case 95: 
        case 96: 
        case 97: 
        case 98: 
        case 99: 
        case 101: 
        case 103: 
        case 104: 
        case 105: 
          {  return symbol(sym.IDEN, new String(yytext()));  }
        case 116: break;
        case 13: 
          {  yybegin(STRING); s = new String(); }
        case 117: break;
        case 41: 
          {  return symbol(sym.VAR, new String(yytext()));  }
        case 118: break;
        case 109: 
          {  return symbol(sym.ORDERED_BY);  }
        case 119: break;
        case 108: 
          {  return symbol(sym.CONFORM_TO);  }
        case 120: break;
        case 107: 
          {  return symbol(sym.CONTENT_AS);  }
        case 121: break;
        case 106: 
          {  return symbol(sym.ELEMENT_AS);  }
        case 122: break;
        case 33: 
          {  s += yytext();  }
        case 123: break;
        case 102: 
          {  return symbol(sym.CONSTRUCT);  }
        case 124: break;
        case 100: 
          {  return symbol(sym.FUNCTION);  }
        case 125: break;
        case 29: 
          {  return symbol(sym.BAR);  }
        case 126: break;
        case 15: 
          {  return symbol(sym.EQ);  }
        case 127: break;
        case 2: 
        case 3: 
        case 8: 
        case 32: 
          {  /* ignore */  }
        case 128: break;
        case 9: 
          {  return symbol(sym.DOT);  }
        case 129: break;
        case 30: 
          {  return symbol(sym.LT);  }
        case 130: break;
        case 31: 
          {  return symbol(sym.GT);  }
        case 131: break;
        case 42: 
          {  return symbol(sym.ID);  }
        case 132: break;
        case 43: 
          {  return symbol(sym.IN);  }
        case 133: break;
        case 47: 
          {  return symbol(sym.OR);  }
        case 134: break;
        case 50: 
          {  return symbol(sym.LEQ);  }
        case 135: break;
        case 51: 
          {  return symbol(sym.GEQ);  }
        case 136: break;
        case 52: 
          {  return symbol(sym.NEQ);  }
        case 137: break;
        case 57: 
          {  return symbol(sym.END);  }
        case 138: break;
        case 61: 
          {  return symbol(sym.NOT);  }
        case 139: break;
        case 65: 
          {  return symbol(sym.AND);  }
        case 140: break;
        case 28: 
          {  return symbol(sym.COLON);  }
        case 141: break;
        case 27: 
          {  return symbol(sym.QMARK);  }
        case 142: break;
        case 26: 
          {  return symbol(sym.COMMA);  }
        case 143: break;
        case 4: 
          {  return symbol(sym.SLASH);  }
        case 144: break;
        case 5: 
          {  return symbol(sym.STAR);  }
        case 145: break;
        case 7: 
          {  return symbol(sym.PLUS);  }
        case 146: break;
        case 60: 
          {  return symbol(sym.IDEQ);  }
        case 147: break;
        case 77: 
          {  return symbol(sym.WHERE);  }
        case 148: break;
        case 34: 
          {  yybegin(YYINITIAL); 
     		  	  return symbol(sym.STRING, s); 
   			 }
        case 149: break;
        case 38: 
        case 54: 
        case 68: 
          {  return symbol(sym.NUMBER,new String(yytext()));  }
        case 150: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }


}
