include ../make.incl

src = 	Client.java			\
        QueryHandler.java  		\
	Server.java			\
	SEServer.java			\
	SEQueryHandler.java		\
	SEClient.java			\
	ConstructIndex.java		\

OBJ = $(src:.java=.class)

all:  $(OBJ) 

classpath:
	@echo $(CLASSPATH)

clean:
	rm -f *.class *~

